# Generated by Django 4.2.5 on 2023-09-16 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('dosis', models.IntegerField()),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
